const DATA = 'data-';
export const DRAG_ID = `${DATA}drag-id`;
export const DRAG_TYPE = `${DATA}drag-type`;
export const DRAG_ACTIVE = `${DATA}drag-active`;
export const DRAG_DISABLED = `${DATA}drag-disabled`;
export const DRAG_SITE = `${DATA}drag-site`;
export const DRAG_GROUP = `${DATA}drag-group`;
export const DRAG_GROUP_ANGLE = `${DATA}drag-group-angle`;
export const DRAG_GROUP_ID = `${DATA}drag-group-id`;